<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>b3ae5fd2-8fbd-4632-8e65-a7ed5426f0a7</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.19" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\host\Codex.ServiceDefaults\Codex.ServiceDefaults.csproj" />
      <ProjectReference Include="..\Codex.Infrastructure\Codex.Infrastructure.csproj" />
    </ItemGroup>

</Project>
